version: '3.7'

volumes:
  grafana-data:
  prometheus-data:

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - /var/log/traefik/traefik.log:/traefik.log
      - /var/log/traefik/traefikAccess.log:/traefikAccess.log
      # Add folder with dynamic configuration yml
      - ./data/configurations:/configurations
    networks:
      - web

  prometheus:
    image: prom/prometheus:v2.12.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
    labels:
       - "traefik.http.routers.prometheus.rule=Host(`prometheus.dehub.tech`)"
       - "traefik.http.routers.prometheus.service=prometheus"
       - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
       - "traefik.docker.network=web"
       
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8008:8080

  grafana:
    image: grafana/grafana:7.0.0
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_INSTALL_PLUGINS: grafana-piechart-panel,jdbranham-diagram-panel
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
        - "traefik.http.routers.grafana.rule=Host(`grafana.dehub.tech`)"
        - "traefik.http.routers.grafana.service=grafana"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.docker.network=web"


networks:
  web:
    external: true
